---
- name: download rbenv repo
  become: yes
  become_user: "{{pac}}-{{user}}"
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/pacs/{{pac}}/users/{{user}}/.rbenv
- name: make rbenv
  become: yes
  become_user: "{{pac}}-{{user}}"
  shell: |
     cd ~/.rbenv && src/configure && make -C src
     echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile
     echo 'eval "$(rbenv init -)"' >> ~/.profile
  args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.rbenv/libexec/rbenv-realpath.dylib"
- name: download ruby build repo
  become: yes
  become_user: "{{pac}}-{{user}}"
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/pacs/{{pac}}/users/{{user}}/.rbenv/plugins/ruby-build
- name: install ruby
  become: yes
  become_user: "{{pac}}-{{user}}"
  shell: |
     . ~/.profile
     rbenv install {{rubyversion}} || exit -1
  args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.rbenv/versions/{{rubyversion}}/bin/ruby"
